# Generated by Django 5.1.1 on 2024-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_comment_movie_remove_comment_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='actors_movies', to='viewer.movie'),
        ),
    ]
