# Generated by Django 5.1.1 on 2024-09-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
    ]
